// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: lexer.jflex

import java.util.*;
import java.io.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer implements ParserTokens {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int NORMAL = 2;
  public static final int COMMENT = 4;
  public static final int LCOMMENT = 6;
  public static final int CODESTRING = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\12\0\1\1\3\2\23\0\1\3\1\4\2\0\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\11\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\0\4\30\1\31\1\32\5\33\1\34"+
    "\10\33\1\35\2\33\1\36\2\33\1\37\1\40\1\41"+
    "\1\42\1\33\1\0\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\33\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\1\33\1\62\1\63\1\64\1\65"+
    "\1\66\1\67\1\70\1\71\1\72\1\73\1\74\1\75"+
    "\1\76\6\0\1\2\u01a2\0\2\2\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\1\1\3\1\4\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\2\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\17\24\1\30\1\31\1\32\1\33\1\1"+
    "\1\34\1\35\1\0\1\36\1\0\1\37\1\40\1\41"+
    "\3\0\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\1\1\51\1\52\1\0\1\15\1\0\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\6\24\1\61\6\24\1\62"+
    "\13\24\1\63\1\64\1\65\1\36\1\15\1\50\1\0"+
    "\1\50\1\15\13\24\1\66\1\24\1\67\17\24\1\70"+
    "\1\24\1\71\1\72\4\24\1\73\1\74\2\24\1\75"+
    "\1\76\13\24\1\77\2\24\1\100\1\101\4\24\1\102"+
    "\2\24\1\103\6\24\1\104\2\24\1\105\2\24\1\106"+
    "\1\107\1\24\1\110\1\111\1\112\1\113\1\114\1\115"+
    "\4\24\1\116\1\24\1\117\2\24\1\120\1\121\1\122"+
    "\1\123";

  private static int [] zzUnpackAction() {
    int [] result = new int[215];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\77\0\176\0\275\0\0\0\374\0\u013b\0\u017a"+
    "\0\u01b9\0\u01f8\0\0\0\0\0\u0237\0\u0276\0\0\0\u02b5"+
    "\0\u02f4\0\u0333\0\u0372\0\u03b1\0\0\0\0\0\u03f0\0\u042f"+
    "\0\u046e\0\0\0\u04ad\0\0\0\0\0\u04ec\0\u052b\0\u056a"+
    "\0\u05a9\0\u05e8\0\u0627\0\u0666\0\u06a5\0\u06e4\0\u0723\0\u0762"+
    "\0\u07a1\0\u07e0\0\u081f\0\u085e\0\u089d\0\0\0\u08dc\0\0"+
    "\0\0\0\u091b\0\0\0\0\0\u013b\0\0\0\u095a\0\0"+
    "\0\0\0\0\0\u0999\0\u09d8\0\u0a17\0\0\0\0\0\0"+
    "\0\0\0\0\0\0\0\u0a56\0\u0a95\0\0\0\0\0\u0ad4"+
    "\0\u0b13\0\u0b52\0\0\0\0\0\0\0\0\0\0\0\0"+
    "\0\u0b91\0\u0bd0\0\u0c0f\0\u0c4e\0\u0c8d\0\u0ccc\0\u0d0b\0\u0d4a"+
    "\0\u0d89\0\u0dc8\0\u0e07\0\u0e46\0\u0e85\0\u04ad\0\u0ec4\0\u0f03"+
    "\0\u0f42\0\u0f81\0\u0fc0\0\u0fff\0\u103e\0\u107d\0\u10bc\0\u10fb"+
    "\0\u113a\0\0\0\0\0\0\0\u013b\0\0\0\0\0\u1179"+
    "\0\u11b8\0\u11f7\0\u1236\0\u1275\0\u12b4\0\u12f3\0\u1332\0\u1371"+
    "\0\u13b0\0\u13ef\0\u142e\0\u146d\0\u14ac\0\u04ad\0\u14eb\0\u04ad"+
    "\0\u152a\0\u1569\0\u15a8\0\u15e7\0\u1626\0\u1665\0\u16a4\0\u16e3"+
    "\0\u1722\0\u1761\0\u17a0\0\u17df\0\u181e\0\u185d\0\u189c\0\u04ad"+
    "\0\u18db\0\u04ad\0\u04ad\0\u191a\0\u1959\0\u1998\0\u19d7\0\u04ad"+
    "\0\u04ad\0\u1a16\0\u1a55\0\u04ad\0\u04ad\0\u1a94\0\u1ad3\0\u1b12"+
    "\0\u1b51\0\u1b90\0\u1bcf\0\u1c0e\0\u1c4d\0\u1c8c\0\u1ccb\0\u1d0a"+
    "\0\u04ad\0\u1d49\0\u1d88\0\u04ad\0\u04ad\0\u1dc7\0\u1e06\0\u1e45"+
    "\0\u1e84\0\u04ad\0\u1ec3\0\u1f02\0\u04ad\0\u1f41\0\u1f80\0\u1fbf"+
    "\0\u1ffe\0\u203d\0\u207c\0\u04ad\0\u20bb\0\u20fa\0\u04ad\0\u2139"+
    "\0\u2178\0\u04ad\0\u04ad\0\u21b7\0\u04ad\0\u04ad\0\u04ad\0\u04ad"+
    "\0\u04ad\0\u04ad\0\u21f6\0\u2235\0\u2274\0\u22b3\0\u04ad\0\u22f2"+
    "\0\u04ad\0\u2331\0\u2370\0\u04ad\0\u04ad\0\u04ad\0\u04ad";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[215];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\77\0\3\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\7\33"+
    "\1\34\1\5\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\33\1\46\1\33\1\47\4\33"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\3\33\1\56"+
    "\1\57\1\60\1\61\12\5\1\62\65\5\1\63\75\5"+
    "\25\0\1\64\51\0\4\65\1\66\33\65\1\67\36\65"+
    "\25\0\1\70\57\0\1\71\16\0\1\72\51\0\7\73"+
    "\1\0\30\73\1\74\36\73\12\0\1\75\4\0\1\5"+
    "\5\0\1\76\64\0\1\77\11\0\1\100\66\0\1\101"+
    "\7\0\1\102\1\103\70\0\2\104\67\0\1\105\4\0"+
    "\1\106\5\0\1\107\67\0\1\104\1\0\2\24\7\0"+
    "\1\110\2\0\2\111\1\112\10\0\1\110\5\0\1\111"+
    "\7\0\1\111\2\0\1\112\24\0\1\104\1\0\2\24"+
    "\7\0\1\110\2\0\2\111\11\0\1\110\5\0\1\111"+
    "\7\0\1\111\35\0\1\113\1\114\76\0\1\115\76\0"+
    "\1\116\1\117\70\0\2\33\6\0\7\33\4\0\30\33"+
    "\31\0\1\120\71\0\2\33\6\0\7\33\4\0\22\33"+
    "\1\121\5\33\24\0\2\33\6\0\7\33\4\0\17\33"+
    "\1\122\10\33\24\0\2\33\6\0\7\33\4\0\1\123"+
    "\6\33\1\124\5\33\1\125\12\33\24\0\2\33\6\0"+
    "\7\33\4\0\4\33\1\126\10\33\1\127\12\33\24\0"+
    "\2\33\6\0\7\33\4\0\12\33\1\130\1\33\1\131"+
    "\10\33\1\132\2\33\24\0\2\33\6\0\7\33\4\0"+
    "\12\33\1\133\2\33\1\134\12\33\24\0\2\33\6\0"+
    "\7\33\4\0\15\33\1\135\12\33\24\0\2\33\6\0"+
    "\7\33\4\0\5\33\1\136\6\33\1\137\13\33\24\0"+
    "\2\33\6\0\7\33\4\0\15\33\1\140\12\33\24\0"+
    "\2\33\6\0\7\33\4\0\4\33\1\141\23\33\24\0"+
    "\2\33\6\0\7\33\4\0\7\33\1\142\1\143\10\33"+
    "\1\144\2\33\1\145\3\33\24\0\2\33\6\0\7\33"+
    "\4\0\26\33\1\146\1\33\24\0\2\33\6\0\7\33"+
    "\4\0\14\33\1\147\13\33\24\0\2\33\6\0\7\33"+
    "\4\0\15\33\1\150\12\33\24\0\2\33\6\0\7\33"+
    "\4\0\7\33\1\151\20\33\31\0\1\152\46\0\1\153"+
    "\21\0\1\154\57\0\4\65\1\155\33\65\1\67\36\65"+
    "\7\0\1\156\67\0\1\73\2\0\74\73\12\0\1\75"+
    "\4\0\1\5\77\0\2\104\7\0\1\110\1\157\1\0"+
    "\1\157\12\0\1\110\1\157\4\0\1\157\21\0\12\105"+
    "\1\0\64\105\13\0\1\160\1\0\1\160\2\0\2\161"+
    "\111\0\2\111\17\0\1\111\7\0\1\111\31\0\2\162"+
    "\6\0\3\162\10\0\6\162\46\0\2\33\6\0\7\33"+
    "\4\0\21\33\1\163\6\33\24\0\2\33\6\0\7\33"+
    "\4\0\4\33\1\164\23\33\24\0\2\33\6\0\7\33"+
    "\4\0\20\33\1\165\7\33\24\0\2\33\6\0\7\33"+
    "\4\0\1\166\27\33\24\0\2\33\6\0\7\33\4\0"+
    "\14\33\1\167\13\33\24\0\2\33\6\0\7\33\4\0"+
    "\5\33\1\170\22\33\24\0\2\33\6\0\7\33\4\0"+
    "\22\33\1\171\5\33\24\0\2\33\6\0\7\33\4\0"+
    "\20\33\1\172\7\33\24\0\2\33\6\0\7\33\4\0"+
    "\22\33\1\173\5\33\24\0\2\33\6\0\7\33\4\0"+
    "\21\33\1\174\6\33\24\0\2\33\6\0\7\33\4\0"+
    "\15\33\1\175\12\33\24\0\2\33\6\0\7\33\4\0"+
    "\17\33\1\176\10\33\24\0\2\33\6\0\7\33\4\0"+
    "\21\33\1\177\6\33\24\0\2\33\6\0\7\33\4\0"+
    "\21\33\1\200\6\33\24\0\2\33\6\0\7\33\4\0"+
    "\14\33\1\201\13\33\24\0\2\33\6\0\7\33\4\0"+
    "\6\33\1\202\12\33\1\203\6\33\24\0\2\33\6\0"+
    "\7\33\4\0\15\33\1\204\12\33\24\0\2\33\6\0"+
    "\7\33\4\0\6\33\1\205\20\33\1\206\24\0\2\33"+
    "\6\0\7\33\4\0\1\207\16\33\1\210\10\33\24\0"+
    "\2\33\6\0\7\33\4\0\10\33\1\211\17\33\24\0"+
    "\2\33\6\0\7\33\4\0\16\33\1\212\11\33\24\0"+
    "\2\33\6\0\7\33\4\0\10\33\1\213\7\33\1\214"+
    "\7\33\24\0\2\33\6\0\7\33\4\0\10\33\1\215"+
    "\1\33\1\216\15\33\24\0\2\33\6\0\7\33\4\0"+
    "\10\33\1\217\17\33\24\0\2\161\75\0\2\161\10\0"+
    "\1\157\1\0\1\157\13\0\1\157\4\0\1\157\41\0"+
    "\2\162\6\0\3\162\1\0\2\111\5\0\6\162\4\0"+
    "\1\111\7\0\1\111\31\0\2\33\6\0\7\33\4\0"+
    "\15\33\1\220\12\33\24\0\2\33\6\0\7\33\4\0"+
    "\1\221\27\33\24\0\2\33\6\0\7\33\4\0\4\33"+
    "\1\222\23\33\24\0\2\33\6\0\7\33\4\0\17\33"+
    "\1\223\10\33\24\0\2\33\6\0\7\33\4\0\20\33"+
    "\1\224\1\225\6\33\24\0\2\33\6\0\7\33\4\0"+
    "\1\226\27\33\24\0\2\33\6\0\7\33\4\0\1\33"+
    "\1\227\26\33\24\0\2\33\6\0\7\33\4\0\4\33"+
    "\1\230\23\33\24\0\2\33\6\0\7\33\4\0\13\33"+
    "\1\231\14\33\24\0\2\33\6\0\7\33\4\0\4\33"+
    "\1\232\23\33\24\0\2\33\6\0\7\33\4\0\1\233"+
    "\27\33\24\0\2\33\6\0\7\33\4\0\15\33\1\234"+
    "\12\33\24\0\2\33\6\0\7\33\4\0\6\33\1\235"+
    "\21\33\24\0\2\33\6\0\7\33\4\0\10\33\1\236"+
    "\17\33\24\0\2\33\6\0\7\33\4\0\22\33\1\237"+
    "\5\33\24\0\2\33\6\0\7\33\4\0\17\33\1\240"+
    "\10\33\24\0\2\33\6\0\7\33\4\0\14\33\1\241"+
    "\13\33\24\0\2\33\6\0\7\33\4\0\4\33\1\242"+
    "\23\33\24\0\2\33\6\0\7\33\4\0\21\33\1\243"+
    "\6\33\24\0\2\33\6\0\7\33\4\0\22\33\1\244"+
    "\5\33\24\0\2\33\6\0\7\33\4\0\21\33\1\245"+
    "\6\33\24\0\2\33\6\0\7\33\4\0\4\33\1\246"+
    "\23\33\24\0\2\33\6\0\7\33\4\0\15\33\1\247"+
    "\12\33\24\0\2\33\6\0\7\33\4\0\10\33\1\250"+
    "\17\33\24\0\2\33\6\0\7\33\4\0\3\33\1\251"+
    "\24\33\24\0\2\33\6\0\7\33\4\0\1\252\27\33"+
    "\24\0\2\33\6\0\7\33\4\0\12\33\1\253\15\33"+
    "\24\0\2\33\6\0\7\33\4\0\11\33\1\254\16\33"+
    "\24\0\2\33\6\0\7\33\4\0\21\33\1\255\6\33"+
    "\24\0\2\33\6\0\7\33\4\0\10\33\1\256\17\33"+
    "\24\0\2\33\6\0\7\33\4\0\22\33\1\257\5\33"+
    "\24\0\2\33\6\0\7\33\4\0\12\33\1\260\15\33"+
    "\24\0\2\33\6\0\7\33\4\0\17\33\1\261\10\33"+
    "\24\0\2\33\6\0\7\33\4\0\21\33\1\262\6\33"+
    "\24\0\2\33\6\0\7\33\4\0\20\33\1\263\7\33"+
    "\24\0\2\33\6\0\7\33\4\0\17\33\1\264\10\33"+
    "\24\0\2\33\6\0\7\33\4\0\21\33\1\265\6\33"+
    "\24\0\2\33\6\0\7\33\4\0\4\33\1\266\23\33"+
    "\24\0\2\33\6\0\7\33\4\0\15\33\1\267\12\33"+
    "\24\0\2\33\6\0\7\33\4\0\10\33\1\270\17\33"+
    "\24\0\2\33\6\0\7\33\4\0\2\33\1\271\25\33"+
    "\24\0\2\33\6\0\7\33\4\0\2\33\1\272\25\33"+
    "\24\0\2\33\6\0\7\33\4\0\3\33\1\273\24\33"+
    "\24\0\2\33\6\0\7\33\4\0\14\33\1\274\13\33"+
    "\24\0\2\33\6\0\7\33\4\0\6\33\1\275\21\33"+
    "\24\0\2\33\6\0\7\33\4\0\21\33\1\276\6\33"+
    "\24\0\2\33\6\0\7\33\4\0\4\33\1\277\23\33"+
    "\24\0\2\33\6\0\7\33\4\0\14\33\1\300\13\33"+
    "\24\0\2\33\6\0\7\33\4\0\12\33\1\301\15\33"+
    "\24\0\2\33\6\0\7\33\4\0\4\33\1\302\23\33"+
    "\24\0\2\33\6\0\7\33\4\0\14\33\1\303\13\33"+
    "\24\0\2\33\6\0\7\33\4\0\21\33\1\304\6\33"+
    "\24\0\2\33\6\0\7\33\4\0\14\33\1\305\13\33"+
    "\24\0\2\33\6\0\7\33\4\0\3\33\1\306\24\33"+
    "\24\0\2\33\6\0\7\33\4\0\5\33\1\307\22\33"+
    "\24\0\2\33\6\0\7\33\4\0\2\33\1\310\25\33"+
    "\24\0\2\33\6\0\7\33\4\0\21\33\1\311\6\33"+
    "\24\0\2\33\6\0\7\33\4\0\7\33\1\312\20\33"+
    "\24\0\2\33\6\0\7\33\4\0\4\33\1\313\23\33"+
    "\24\0\2\33\6\0\7\33\4\0\14\33\1\314\13\33"+
    "\24\0\2\33\6\0\7\33\4\0\10\33\1\315\17\33"+
    "\24\0\2\33\6\0\7\33\4\0\22\33\1\316\5\33"+
    "\24\0\2\33\6\0\7\33\4\0\21\33\1\317\6\33"+
    "\24\0\2\33\6\0\7\33\4\0\4\33\1\320\23\33"+
    "\24\0\2\33\6\0\7\33\4\0\5\33\1\321\22\33"+
    "\24\0\2\33\6\0\7\33\4\0\4\33\1\322\23\33"+
    "\24\0\2\33\6\0\7\33\4\0\12\33\1\323\15\33"+
    "\24\0\2\33\6\0\7\33\4\0\4\33\1\324\23\33"+
    "\24\0\2\33\6\0\7\33\4\0\17\33\1\325\10\33"+
    "\24\0\2\33\6\0\7\33\4\0\3\33\1\326\24\33"+
    "\24\0\2\33\6\0\7\33\4\0\4\33\1\327\23\33"+
    "\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9135];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\10\3\0\1\11\5\1\2\11\2\1\1\11\5\1"+
    "\2\11\3\1\1\11\1\1\2\11\20\1\1\11\1\1"+
    "\2\11\1\1\2\11\1\0\1\11\1\0\3\11\3\0"+
    "\6\11\2\1\2\11\1\0\1\1\1\0\6\11\31\1"+
    "\3\11\1\1\2\11\1\0\147\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[215];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private int token;
    private helper semantic;
    public int lineNum;
    public int colNum;
    
    public int getToken()
    {
        return token;
    }

    public int getlineNum()
    {
        return lineNum;
    }

    public int getcolNum()
    {
        return colNum;
    }

    public helper getSemantic()
    {
        return semantic;
    }

    public int nextToken()
    {
        try
        {
            token = yylex();
        }
        catch (java.io.IOException e)
        {
            System.out.println(
                "IO exception occured:\n" + e);
        }
        return token;
    }

    public boolean getzzAtEOF()
    {
        return zzAtEOF;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
      yybegin(NORMAL);
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case NORMAL: {
              return ENDINPUT;
            }  // fall though
            case 216: break;
            case COMMENT: {
              return ENDINPUT;
            }  // fall though
            case 217: break;
            case LCOMMENT: {
              return ENDINPUT;
            }  // fall though
            case 218: break;
            default:
        return YYEOF;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { ;
            }
            // fall through
          case 84: break;
          case 2:
            { semantic = new helper(yytext()); return '!';
            }
            // fall through
          case 85: break;
          case 3:
            { semantic = new helper(yytext()); return '%';
            }
            // fall through
          case 86: break;
          case 4:
            { semantic = new helper(yytext()); return '&';
            }
            // fall through
          case 87: break;
          case 5:
            { semantic = new helper(yytext()); return '(';
            }
            // fall through
          case 88: break;
          case 6:
            { semantic = new helper(yytext()); return ')';
            }
            // fall through
          case 89: break;
          case 7:
            { semantic = new helper(yytext()); return '*';
            }
            // fall through
          case 90: break;
          case 8:
            { semantic = new helper(yytext()); return '+';
            }
            // fall through
          case 91: break;
          case 9:
            { semantic = new helper(yytext()); return ',';
            }
            // fall through
          case 92: break;
          case 10:
            { semantic = new helper(yytext()); return '-';
            }
            // fall through
          case 93: break;
          case 11:
            { semantic = new helper(yytext()); return '.';
            }
            // fall through
          case 94: break;
          case 12:
            { semantic = new helper(yytext()); return '/';
            }
            // fall through
          case 95: break;
          case 13:
            { semantic = new helper(yytext()); return I_CONSTANT;
            }
            // fall through
          case 96: break;
          case 14:
            { semantic = new helper(yytext()); return ':';
            }
            // fall through
          case 97: break;
          case 15:
            { semantic = new helper(yytext()); return ';';
            }
            // fall through
          case 98: break;
          case 16:
            { semantic = new helper(yytext()); return '<';
            }
            // fall through
          case 99: break;
          case 17:
            { semantic = new helper(yytext()); return '=';
            }
            // fall through
          case 100: break;
          case 18:
            { semantic = new helper(yytext()); return '>';
            }
            // fall through
          case 101: break;
          case 19:
            { semantic = new helper(yytext()); return '?';
            }
            // fall through
          case 102: break;
          case 20:
            { semantic = new helper(yytext()); return IDENTIFIER;
            }
            // fall through
          case 103: break;
          case 21:
            { semantic = new helper(yytext()); return '[';
            }
            // fall through
          case 104: break;
          case 22:
            { semantic = new helper(yytext()); return ']';
            }
            // fall through
          case 105: break;
          case 23:
            { semantic = new helper(yytext()); return '^';
            }
            // fall through
          case 106: break;
          case 24:
            { semantic = new helper(yytext()); return '{';
            }
            // fall through
          case 107: break;
          case 25:
            { semantic = new helper(yytext()); return '|';
            }
            // fall through
          case 108: break;
          case 26:
            { semantic = new helper(yytext()); return '}';
            }
            // fall through
          case 109: break;
          case 27:
            { semantic = new helper(yytext()); return '~';
            }
            // fall through
          case 110: break;
          case 28:
            { yybegin(NORMAL);
            }
            // fall through
          case 111: break;
          case 29:
            { semantic = new helper(yytext()); return NE_OP;
            }
            // fall through
          case 112: break;
          case 30:
            { semantic = new helper(yytext()); return STRING_LITERAL;
            }
            // fall through
          case 113: break;
          case 31:
            { semantic = new helper(yytext()); return MOD_ASSIGN;
            }
            // fall through
          case 114: break;
          case 32:
            { semantic = new helper(yytext()); return AND_OP;
            }
            // fall through
          case 115: break;
          case 33:
            { semantic = new helper(yytext()); return AND_ASSIGN;
            }
            // fall through
          case 116: break;
          case 34:
            { semantic = new helper(yytext()); return MUL_ASSIGN;
            }
            // fall through
          case 117: break;
          case 35:
            { semantic = new helper(yytext()); return INC_OP;
            }
            // fall through
          case 118: break;
          case 36:
            { semantic = new helper(yytext()); return ADD_ASSIGN;
            }
            // fall through
          case 119: break;
          case 37:
            { semantic = new helper(yytext()); return DEC_OP;
            }
            // fall through
          case 120: break;
          case 38:
            { semantic = new helper(yytext()); return SUB_ASSIGN;
            }
            // fall through
          case 121: break;
          case 39:
            { semantic = new helper(yytext()); return PTR_OP;
            }
            // fall through
          case 122: break;
          case 40:
            { semantic = new helper(yytext()); return F_CONSTANT;
            }
            // fall through
          case 123: break;
          case 41:
            { yybegin(LCOMMENT);
            }
            // fall through
          case 124: break;
          case 42:
            { semantic = new helper(yytext()); return DIV_ASSIGN;
            }
            // fall through
          case 125: break;
          case 43:
            { semantic = new helper(yytext()); return LEFT_OP;
            }
            // fall through
          case 126: break;
          case 44:
            { semantic = new helper(yytext()); return LE_OP;
            }
            // fall through
          case 127: break;
          case 45:
            { semantic = new helper(yytext()); return EQ_OP;
            }
            // fall through
          case 128: break;
          case 46:
            { semantic = new helper(yytext()); return GE_OP;
            }
            // fall through
          case 129: break;
          case 47:
            { semantic = new helper(yytext()); return RIGHT_OP;
            }
            // fall through
          case 130: break;
          case 48:
            { semantic = new helper(yytext()); return XOR_ASSIGN;
            }
            // fall through
          case 131: break;
          case 49:
            { semantic = new helper(yytext()); return DO;
            }
            // fall through
          case 132: break;
          case 50:
            { semantic = new helper(yytext()); return IF;
            }
            // fall through
          case 133: break;
          case 51:
            { semantic = new helper(yytext()); return OR_ASSIGN;
            }
            // fall through
          case 134: break;
          case 52:
            { semantic = new helper(yytext()); return OR_OP;
            }
            // fall through
          case 135: break;
          case 53:
            { yybegin( NORMAL );
            }
            // fall through
          case 136: break;
          case 54:
            { semantic = new helper(yytext()); return FOR;
            }
            // fall through
          case 137: break;
          case 55:
            { semantic = new helper(yytext()); return INT;
            }
            // fall through
          case 138: break;
          case 56:
            { semantic = new helper(yytext()); return AUTO;
            }
            // fall through
          case 139: break;
          case 57:
            { semantic = new helper(yytext()); return CASE;
            }
            // fall through
          case 140: break;
          case 58:
            { semantic = new helper(yytext()); return CHAR;
            }
            // fall through
          case 141: break;
          case 59:
            { semantic = new helper(yytext()); return ELSE;
            }
            // fall through
          case 142: break;
          case 60:
            { semantic = new helper(yytext()); return ENUM;
            }
            // fall through
          case 143: break;
          case 61:
            { semantic = new helper(yytext()); return GOTO;
            }
            // fall through
          case 144: break;
          case 62:
            { semantic = new helper(yytext()); return LONG;
            }
            // fall through
          case 145: break;
          case 63:
            { semantic = new helper(yytext()); return VOID;
            }
            // fall through
          case 146: break;
          case 64:
            { semantic = new helper(yytext()); return BREAK;
            }
            // fall through
          case 147: break;
          case 65:
            { semantic = new helper(yytext()); return CONST;
            }
            // fall through
          case 148: break;
          case 66:
            { semantic = new helper(yytext()); return FLOAT;
            }
            // fall through
          case 149: break;
          case 67:
            { semantic = new helper(yytext()); return SHORT;
            }
            // fall through
          case 150: break;
          case 68:
            { semantic = new helper(yytext()); return UNION;
            }
            // fall through
          case 151: break;
          case 69:
            { semantic = new helper(yytext()); return WHILE;
            }
            // fall through
          case 152: break;
          case 70:
            { semantic = new helper(yytext()); return DOUBLE;
            }
            // fall through
          case 153: break;
          case 71:
            { semantic = new helper(yytext()); return EXTERN;
            }
            // fall through
          case 154: break;
          case 72:
            { semantic = new helper(yytext()); return RETURN;
            }
            // fall through
          case 155: break;
          case 73:
            { semantic = new helper(yytext()); return SIGNED;
            }
            // fall through
          case 156: break;
          case 74:
            { semantic = new helper(yytext()); return SIZEOF;
            }
            // fall through
          case 157: break;
          case 75:
            { semantic = new helper(yytext()); return STATIC;
            }
            // fall through
          case 158: break;
          case 76:
            { semantic = new helper(yytext()); return STRUCT;
            }
            // fall through
          case 159: break;
          case 77:
            { semantic = new helper(yytext()); return SWITCH;
            }
            // fall through
          case 160: break;
          case 78:
            { semantic = new helper(yytext()); return DEFAULT;
            }
            // fall through
          case 161: break;
          case 79:
            { semantic = new helper(yytext()); return TYPEDEF;
            }
            // fall through
          case 162: break;
          case 80:
            { semantic = new helper(yytext()); return CONTINUE;
            }
            // fall through
          case 163: break;
          case 81:
            { semantic = new helper(yytext()); return REGISTER;
            }
            // fall through
          case 164: break;
          case 82:
            { semantic = new helper(yytext()); return UNSIGNED;
            }
            // fall through
          case 165: break;
          case 83:
            { semantic = new helper(yytext()); return VOLATILE;
            }
            // fall through
          case 166: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
